// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8RSpKsByBfbvNQfV9oI9sIWBhnjF_EvA',
    appId: '1:748384472935:web:0e0815dcfc9db51a1969c2',
    messagingSenderId: '748384472935',
    projectId: 'school-c3b09',
    authDomain: 'school-c3b09.firebaseapp.com',
    storageBucket: 'school-c3b09.appspot.com',
    measurementId: 'G-ZJEL9SWJ2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoESDIizfTvlfZOQ955fkQ8ao_HbbfQ7Y',
    appId: '1:748384472935:android:91370a3c3ff724501969c2',
    messagingSenderId: '748384472935',
    projectId: 'school-c3b09',
    storageBucket: 'school-c3b09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnD7nuugM3p3qJ7nHqf9sQpJX7-a-2f1I',
    appId: '1:748384472935:ios:f4c45a51cf8693281969c2',
    messagingSenderId: '748384472935',
    projectId: 'school-c3b09',
    storageBucket: 'school-c3b09.appspot.com',
    iosBundleId: 'com.example.school',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnD7nuugM3p3qJ7nHqf9sQpJX7-a-2f1I',
    appId: '1:748384472935:ios:f4c45a51cf8693281969c2',
    messagingSenderId: '748384472935',
    projectId: 'school-c3b09',
    storageBucket: 'school-c3b09.appspot.com',
    iosBundleId: 'com.example.school',
  );
}
